### ISSUE TITLE
autobuild-aoscarchive:  -z : command not found.

### ISSUE THREAD

**Issue by FlyGoat** [AOSC-Dev/autobuild3#103]
Commit: 307ad74c42e883d3924d9971843b303b2f157654 introduced overlay support
However, this change caused such error report:
```
/bin/autobuild-aoscarchive: line 48:  -z : command not found
/bin/autobuild-aoscarchive: line 48:  -z : command not found
```
I'm not familiar with bash scripts, so I'm asking for further investigate.
Thanks.

**Comment by MingcongBai** [comment]
I think a bracket around the expression should suffice.
