### ISSUE TITLE
$pkgbase-like support

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#12]
We need something like Archlinux's pkgbase.

**Comment by MingcongBai** [comment]
Please go ahead.

-----原始邮件-----
发件人: "Mingye Wang" <notifications@github.com>
发送时间: ‎2015/‎1/‎5 19:11
收件人: "AOSC-Dev/autobuild3" <autobuild3@noreply.github.com>
主题: [autobuild3] $pkgbase-like support (#12)

We need something like Archlinux's pkgbase.

**Comment by MingcongBai** [comment]
This will be solved with the sequential build functionality of abbs. And this is already been implemented. Closing this issue.
