### ISSUE TITLE
NOSTATIC

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/autobuild3#13]
A switch for purging all static libraries from the package building area, which defaults to "NO".

What do you guys think? @Arthur2e5 @butangmucat @Icenowy

**Comment by Arthur2e5** [comment]
考虑和自动拆包一起出。。
还有自动生成 debug 用等效包什么的

**Comment by MingcongBai** [comment]
Debug 包确实想过一段时间了...... Use English shall we

-----原始邮件-----
发件人: "Mingye Wang" <notifications@github.com>
发送时间: ‎2015/‎1/‎11 19:14
收件人: "AOSC-Dev/autobuild3" <autobuild3@noreply.github.com>
抄送: "Jeff Bai" <jeffbaichina@members.fsf.org>
主题: Re: [autobuild3] NOSTATIC (#13)

考虑和自动拆包一起出。。
还有自动生成 debug 用等效包什么的
