### ISSUE TITLE
TODOs from 20150430 Discussion (Possibly Path to AB3.5)

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/autobuild3#20]
Just a list of notes taken from the discussion.

Regarding current features and code:
1. Clarifying the obscure code in part of autobuild3, comments of codes, and documentations (possibly a rework of TechBase article)
2. Unit testing implementation for most of the functions.
~~3. Indent, fix to 8 spaces or full tab.~~ Done.

Regarding future features for autobuild3.5:
1. Rework of abbaselib, extraction of AOSC specific codes.
2. Derive warning and error level into strict mode and possibly a lessened mode.
3. Split functions of autobuild and AOSC packaging QA.
~~4. Possible template system.~~ Moved to abbs-utils.
~~5. Possible PKGBUILD backend and bi-directional translation of both types of configurations.~~ For autobuild4.

The initial discussion is ENDED. But further discussion regarding the "wet" practices welcome.

@Icenowy @Arthur2e5

**Comment by MingcongBai** [comment]
Just a list of notes taken from the discussion.

Regarding current features and code:
1. Clarifying the obscure code in part of autobuild3, comments of codes, and documentations (possibly a rework of TechBase article)
2. Unit testing implementation for most of the functions.
3. Indent, fix to 8 spaces or full tab.

Regarding future features for autobuild3.5:
1. Rework of abbaselib, extraction of AOSC specific codes.
2. Derive warning and error level into strict mode and possibly a lessened mode.
3. Split functions of autobuild and AOSC packaging QA.
4. Possible template system.
5. Possible PKGBUILD backend and bi-directional translation of both types of configurations.

The initial discussion is ENDED. But further discussion regarding the "wet" practices welcome.

**Comment by MingcongBai** [comment]
Gone through all the codes during my Literature class... totally worth it.

**Comment by MingcongBai** [comment]
Would you like to lend a hand? @AOSC-Dev/owners @AOSC-Dev/commiters

**Comment by Arthur2e5** [comment]
I hate sourcing files for every step involved in packing…

**Comment by MingcongBai** [comment]
Sorry if this sounds like a drama...

@Icenowy says, autobuild3 has some design flaws on its infrastructure and he knows it...

Please do not quit a conversation with a question on your other peer. This has caused partial discomfort on my part and misunderstanding on @Icenowy part. 

Definitely appreciate your work and help, that's what I want to say.

**Comment by MingcongBai** [comment]
Templates system will be a part of abbs-utils.
