### ISSUE TITLE
Epoch ":" handling

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/autobuild3#21]

**Comment by Arthur2e5** [comment]
There are some TO-Discuss in autobuild.

## Which way shall we treat as the standard?

## How shall we rewrite the PKGREL integer when it was splitted from the PKGVER string? 

```Bash
# Pseudocode is always the most realistic thing.
_ext_done verlint || warn VERSION not linted.

# when pkgver stuffs is default..
dump_pkgver(){
    echo -n PKGVER=
    (( PKGEPOCH )) && echo -n $PKGEPOCH:
    echo -n $PKGVER
    (( PKGREL )) && echo -n $PKGREL
}

# and when splitting is the default:
dump_verinfo(){
    (( PKGREL )) && echo -n PKGREL=$PKGREL
    echo -n PKGVER=$PKGVER
    (( PKGEPOCH )) && echo -n PKGEPOCH=$PKGEPOCH
}

# START PROCESSING
buf="$(dump_$_ab_formatset)"

# guess format
if ((_ext_versplit_orig_noepoch)); then
  if ((_ext_versplit_orig_norelease)); then	# PKGVER ONLY
    head="$(grep -B9999 '^PKGVER=' autobuild/defines | head -n +1)"
    tail="$(grep -A9999 '^PKGVER=' autobuild/defines | tail -n +1)"
  else								# HAS RELEASE, 
    head=
  fi
else									# NEWTYPE, 

fi
echo "$head
$buf
$tail" > autobuild/defines
```

### Current Problems
The current grep method may look fine for regular human-written scripts, with orders like `[EPOCH]\nVER\n[REL]`. However, this can never be assumed easily.

One way is to import it using `show_differences_from_to "$(bash --norc -c '. autobuild/defines; set)"  "$(bash --norc -c set)"`, so we know what variables are added to the file. However, just like the `declare -f` method in `pkg2ab`, we lose sorting and comments in the original file.

**Comment by MingcongBai** [comment]
It works as far as now. Closing, please open a new one with upcoming issues.
