### ISSUE TITLE
Consider using (( )) instead of bool.

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#22]
Additional Header:
```Bash
readonly true=1 false=0
```

Usage:
```Bash
# if bool $p
if ((p))
```

Doing this would limit the safely-accepted ranges from ([01]|t(rue|)|f(alse|)|y(es|)|n(o|)) to (\d*|true|false). This may help clearify some definitions by reducing the possibilities allowed.

The old bool can be kept for reading user input.

**Comment by Arthur2e5** [comment]
This is basically done.

**Comment by Icenowy** [comment]
鲁棒性不足

**Comment by Icenowy** [comment]
鲁棒性不足

**Comment by Arthur2e5** [comment]
Your implementation suck more.
