### ISSUE TITLE
Extended autotools support with metadata, TODO

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#32]
Two arguments.

```Bash
. /etc/lsb_release
dumpver(){ ((PKGEPOCH)) && echo -n $PKGEPOCH:; echo -n $PKGVER; ((PKGREL)) && echo -n -$PKGREL; }
AUTOTOOLS_DEF+="--with-pkgversion='$(dumpver)_$DISTRIB_ID' --with-bugurl=https://bugs.anthonos.org "
```

Also check if there is something like that with cmake.

And shall we use `--disable-option-checking`?

**Comment by MingcongBai** [comment]
@Arthur2e5

That would be useful if it is not real GNU autotools included in the source. But no, if the configure script is not GNU autotools gemerated, then this is worthless.

**Comment by Arthur2e5** [comment]
Added `$BUGURL` so `abbs` can use the repo's stuff to override it.
