### ISSUE TITLE
Respect custom shebangs in abscripts.

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#42]
When we see them, we should do nothing but adding it to an array and let elfdep handle it later.

- [ ] Recognize she-bangs
 - [ ] Parse `env` linuxly.
- [ ] abscripts handling for those languages

**Comment by MingcongBai** [comment]
Why `elfdep`?

**Comment by Arthur2e5** [comment]
@MingcongBai Because it searches for packages that provides a specific files and we can let it help us.

Just a mean of *too lazy to write it twice*.

**Comment by MingcongBai** [comment]
Well, well. That's acceptable though, although not exactly pretty.

**Comment by Arthur2e5** [comment]
Extra question to solve added. Removing from milestone.

**Comment by Arthur2e5** [comment]
This doesn't make sense for our current construction. Consider some `lua /usr/share/blah`.
