### ISSUE TITLE
autobuild/alternatives not working with RPM packages

### ISSUE THREAD

**Issue by butangmucat** [AOSC-Dev/autobuild3#44]
I was building mksh and I noticed that autobuild/alternatives was working with deb packages in BuildKit but not with my RPM desktop installation. The alternatives defined in this file does not seem to take effect when installing the RPM version of the package.

Update: when hard-code update-alternatives command into postinst, I got this:

*update-alternatives: error: cannot scan directory '/var/lib/dpkg/alternatives': No such file or directory*

**Comment by Arthur2e5** [comment]
Personally I believe auto build always writes to its scripts with `alternative`, at least all our current versions do.

No PM-specific scripts are supported, therefore it should be global, and I am expecting the same error in RPM installation.

It seems that we should do more research on packing `update-alternatives`.

**Comment by butangmucat** [comment]
I believe that this problem might lie in the RPM OS build itself then. Maybe the error message has a clue.

**Comment by Arthur2e5** [comment]
AOSC-Dev/aosc-os-abbs#35
@butangmucat Look into `abspec` and see if `alternatives` have generated those pre/post actions.

**Comment by butangmucat** [comment]
@Arthur2e5 the bug lies with the rpm system itself, closing.

**Comment by MingcongBai** [comment]
This is actually fixed with https://github.com/AOSC-Dev/aosc-os-abbs/commit/b797120d3866ed33a558cd4e0613092355cbe57d as `update-alternatives` is now splitted from `dpkg`.

**Comment by MingcongBai** [comment]
However, intervention will be needed for `rpm` to depend on `update-alternatives`.

**Comment by MingcongBai** [comment]
In which case `rpm` does depend on `update-alternatives`. Problem solved.
