### ISSUE TITLE
Obj-C/++ compiler support.

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#45]
All I need is the name of that commonly-recognized env var.

**Comment by MingcongBai** [comment]
Like?

**Comment by Arthur2e5** [comment]
http://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Objective-C_002b_002b-Compiler.html
http://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Objective-C-Compiler.html
`OBJC`, `OBJCFLAGS`, `OBJCXX`, `OBJCXXFLAGS`.

一点创意都没有！

**Comment by MingcongBai** [comment]
Well.

**Comment by Arthur2e5** [comment]
Basic impls done! `11-compiler.sh` is too much crap to take care of though.

**Comment by MingcongBai** [comment]
Good here.
