### ISSUE TITLE
13-versionmeta.sh causes AUTOTOOLS to fail

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/autobuild3#54]
`13-versionmeta.sh` apparently fails `autotools`.

```
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: OS'
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
```

`configure` will eventually fail.

**Comment by Arthur2e5** [comment]
Reconsider the suggestion on whitespace-free `DISTRIB_ID`.

**Comment by Arthur2e5** [comment]
No sane fixes can be performed due to the nature of word splitting:
```Bash
p="'q a'"
printf '<%q>\n' $p
# <\'q>
# <a\'>
```

For a temporary fix, I am replacing spaces with underlines.
