### ISSUE TITLE
need an extra subroutine to automatically update the autotools aux files for some new archs

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#67]
We can get the name of the aux files either by reading `configure.{ac,in}` or by crude list-and-guessing.

**Comment by MingcongBai** [comment]
Honestly `autoreconf` will take care of everything...

**Comment by Arthur2e5** [comment]
Last time you didn't say so..

**Comment by Arthur2e5** [comment]
Remember that? You said like on `armel` you need to replace the aux files manually, or configure fails…

**Comment by MingcongBai** [comment]
That was me being stupid or hopelessly high on meth... probably.
