### ISSUE TITLE
arch_loaddef cannot perform correctly as designed

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/autobuild3#70]
look at the original arch_loaddef
Why is ARCH_FINDFILELIST reverted before finding and sourceing?
Because autobuild/x/defines can override autobuild/defines

Commit 9cbdb1229e9fe8754774aea2ffb0e18421acfe14  broken this feature, and make arch_loaddef a nonsense, as the specified defines will be override by the general one.

**Comment by Arthur2e5** [comment]
Loaddef uses loadfiles internally, which does not stop on found. Read the current one and come back.

**Comment by Icenowy** [comment]
I don't mean you can have no main defines but sub-defines, but I mean that sub-defines can patch to main defines

**Comment by Icenowy** [comment]
For example, for arch amd64,mipsel,blah, PKGDEP=a b c, but for armel, d is also needed. I can write 
autobuild/defines: PKGDEP="a b c"
autobuild/armel/defines: PKGDEP+=" d"

**Comment by Icenowy** [comment]
At last, do not change the program logic, unless you know why it's written.

**Comment by Arthur2e5** [comment]
RedBullshit. Luke it.

**Comment by MingcongBai** [comment]
> RedBullshit. Luke it.

But it really did not work.

**Comment by Arthur2e5** [comment]
Fine, tracing.

**Comment by Arthur2e5** [comment]
It does work.
Minimal reproduction code used:
```Bash
ARCH_FINDFILELIST=("autobuild/cross-$ARCH-$CROSS" "autobuild/cross-$CROSS" "autobuild/$ARCH" "autobuild")
ARCH=amd128
arch_loadfiles(){
	local _archpath _archpidx _archokay=0
	for (( _archpidx = "${#ARCH_FINDFILELIST[@]}"; _archpidx; --_archpidx ))
	do
		_archpath="${ARCH_FINDFILELIST[$_archpidx]}"
		if [ -e "$_archpath/$1" ]; then
			. "$_archpath/$1"
			_archokay=1
		fi
	done
	(( _archokay )) || return 127
}
arch_loaddef(){ arch_loadfiles defines; }

cd "$(mktemp -d)"
mkdir -p autobuild/amd128
echo echo a > autobuild/defines
echo echo amd128 > autobuild/amd128/defines
arch_loaddef
```

**Comment by Icenowy** [comment]
define is not plain echo

**Comment by Arthur2e5** [comment]
FUCKING (PLACE IN AUSTRIA) GIVE ME A TEST CASE

**Comment by MingcongBai** [comment]
@Arthur2e5 Please do not close this yet, I am investigating this issue.

**Comment by MingcongBai** [comment]
@Arthur2e5 Test case is `extra-gnome/nautilus`.

**Comment by Arthur2e5** [comment]
AND DEFINE IS NOT PLAIN ECHO BUT THOSE ARE ALL CODE RUN

**Comment by Arthur2e5** [comment]
If you want it, fine, change `echo` to `PKGFAK+=a` and see

**Comment by Icenowy** [comment]
CODE SHOULD NOT ONLY RUNS, BUT ALSO RUN IN A SPECIFIED SEQUENCE. DO YOU THINK A GENERAL defines CAN OVERRIDE WHAT IS DEFINED IN A SPECIFIED ONE?

**Comment by Arthur2e5** [comment]
IT DID NOT COULD YOU PLEASE FUCKING READ THE OUTPUT?

**Comment by MingcongBai** [comment]
Okay, gotcha.

**Comment by MingcongBai** [comment]
... oh...?

**Comment by MingcongBai** [comment]
Okay, gotcha.

**Comment by MingcongBai** [comment]
Let me make a test case real soon...

**Comment by MingcongBai** [comment]
... oh...?

**Comment by Icenowy** [comment]
I've tested it

**Comment by MingcongBai** [comment]
Let me make a test case real soon...

**Comment by Icenowy** [comment]
永远没有把bug assign给用户的做法

**Comment by Icenowy** [comment]
I've tested it

**Comment by Icenowy** [comment]
永远没有把bug assign给用户的做法

**Comment by Arthur2e5** [comment]
@JeffBai 咦，发生什么了

**Comment by Arthur2e5** [comment]
我倒是知道有个设计纰漏
也就是 ab/cross-$CROSS 和 ab/$ARCH
意味着在 armel 上打包 armel 的时候你不能用 cross 过来的那个，反之亦然
但很可惜不是我的锅
总之关我肉棒事…（
自己留下了个垃圾设计现在又装孙，啊不装用户

So go mkfs yourself luser.
