### ISSUE TITLE
AB_FLAGS_XXX do not work in defines

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/autobuild3#72]
as the title says
test case is extra-libs/js-24

**Comment by MingcongBai** [comment]
This issue is most possibly introduced by the faulty fix for #64. I will assign myself on this.

**Comment by Arthur2e5** [comment]
As mentioned in IRC, flag-dependent decisions in `arch/_common.sh` should be moved into another file to be sourced after `arch_loaddef`.

**Comment by MingcongBai** [comment]
Yes, I will do that as planned, just a minute.

**Comment by MingcongBai** [comment]
> As mentioned in IRC, flag-dependent decisions in arch/_common.sh should be moved into another file to be sourced after arch_loaddef.

Just making sure, I will move the parts with

```
...
if ((AB_FLAGS_PIE)); then LDFLAGS_COMMON+='-fPIE -pie ' CFLAGS_COMMON+='-fPIE '; fi
if ((AB_FLAGS_SSP)); then CFLAGS_COMMON+='-fstack-protector-strong --param=ssp-buffer-size=4 '; fi
if ((AB_FLAGS_RRO)); then LDFLAGS_COMMON+='-Wl,-z,relro '; fi
if ((AB_FLAGS_NOW)); then LDFLAGS_COMMON+='-Wl,-z,now '; fi
...
```

To another file sourced after defines, right?

**Comment by Arthur2e5** [comment]
Yes. If there is any other logical decision that involves flag(s) changable by `defines`, move them too.

**Comment by MingcongBai** [comment]
> Yes. If there is any other logical decision that involves flag(s) changable by defines, move them too.

Understood and clear.

**Comment by MingcongBai** [comment]
Issue fix on HEAD. Closing.
