### ISSUE TITLE
Do we really need to break etc/defaults into parts?

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#75]
Normal people use significant comments in the config file to make things easier.

**Comment by Icenowy** [comment]
yes, but this feature is wasted now

**Comment by Arthur2e5** [comment]
So let's merge it.

**Comment by Icenowy** [comment]
no

**Comment by Icenowy** [comment]
you'd use it

**Comment by Icenowy** [comment]
it's for the modularization of ab3

**Comment by Arthur2e5** [comment]
Modularization is nowhere, and we can source modules' scripts in the big config. So go to hell.

**Comment by Icenowy** [comment]
or you can implement defaults and defaults.d

**Comment by Icenowy** [comment]
you can merge it now, but the support of divided defaults should still be dupported

**Comment by Arthur2e5** [comment]
defaults.d can be put in defaults. And go to hell.

**Comment by Icenowy** [comment]
future import of 3rd modules must be present, even if the offical ab3 is solid

**Comment by Icenowy** [comment]
you need prevent the offical files to be modified

**Comment by Icenowy** [comment]
you can implenment the process of defaults.d in defaults, I won't deny
