### ISSUE TITLE
RPM additional dep feature deleted since ab2-port

### ISSUE THREAD

**Issue by Icenowy** [AOSC-Dev/autobuild3#78]
Today, when I'm trying to change a copy of AOSC OS GNOME (Core 3.0.4, updated to 3.2.0), I met such error:

```
root [ / ] ! zypper install glibc tzdata bash
正在加载软件源数据...
正在读取已安装的软件包...
正在解决软件包依赖关系...

问题：readline-6.3.008-6.x86_64 requires rtld(GNU_HASH), but this requirement cannot be provided
  uninstallable providers: glibc-2.19-1.x86_64[AOSC OS3]
                   glibc-2.21-0.x86_64[AOSC OS3]
                   glibc-2.21-1.x86_64[AOSC OS3]
                   glibc-2.21-2.x86_64[AOSC OS3]
                   glibc-2.22-0.x86_64[AOSC OS3]
解决方案 1：Following actions will be done:
  do not install glibc-2.22-2.x86_64
  do not install tzdata-2015f-0.x86_64
  do not install bash-4.3.42-1.x86_64
解决方案 2：break readline-6.3.008-6.x86_64 by ignoring some of its dependencies


```

Then I found that rtld(GNU_HASH) is missing from glibc-2.22-2.x86_64.

I checked aosc-os-core, and found the RPMEXTRAPROVIDES line is still there.

Then I checked pm/rpm/pack, but codes of RPMEXTRAPROVIDES disappeared.

Maybe another problems will also exist in rpm packages. Further review wanted.

pia @Arthur2e5 for the always-unprecise code "beautifying" (and always miss some important parts)

maybe resolved by commit ccbb5113e0319a14116a1dee26599cb3ec410e95 , but we'd check it

**Comment by Icenowy** [comment]
Known rebuild list: (may change)

```
glibc
gjs
```

**Comment by Arthur2e5** [comment]
Rebuilding is an aosc-os-abbs thing.

**Comment by Arthur2e5** [comment]
Oops. I think you should just review the ab2-port merge commit.

**Comment by Arthur2e5** [comment]
Just check c10a0e3.

**Comment by Icenowy** [comment]
In addition, RPMEPOCH support is also dropped, unfortunately

**Comment by Arthur2e5** [comment]
I have personally determined that having a separate RPMEPOCH is a terrible design failure long ago, since it messes up with `pm_getver`.

**Comment by Icenowy** [comment]
but rpm has some traditional epochs.
fsck some hat

- 发送自我的Sony Xperia™智能手机

---- Mingye Wang编写 ----

I have personally determined that having a separate RPMEPOCH is a terrible design failure long ago, since it messes up with `pm_getver`.

---

**Comment by Arthur2e5** [comment]
The current PKGEPOCH design is integer-only. Just made to fit RPM.

**Comment by Arthur2e5** [comment]
Complete as of 132bdda.
