### ISSUE TITLE
cross-$ARCH-$CROSS is not straightforward

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#82]
A quick scan using `echo **/cross-*-*/` on `core` and `abbs` shows that nobody is using this dirname. So we are free to change it.

Perhaps `cross-$CROSS@$ARCH`?

* * *

Actually I prefer some suffix-based naming, but that's gonna cause a lot of renaming, i.e.:

* `ARCH` was `ARCH`.
* `ARCH-cross` was `cross-ARCH`.
* `ARCH-cross-BUILDHOST` was `cross-BUILDHOST-ARCH`.

With this scheme, `ls` sorting makes more sense.

**Comment by MingcongBai** [comment]
So there will be multiple build config for build hosts, for one cross target?

**Comment by Arthur2e5** [comment]
There was support for that already, but the naming is just crap…

**Comment by Arthur2e5** [comment]
The renaming should be straightforward anyway, assuming in `abbs` nobody references other arches' build files…

```sh
for r in aosc-os-*; do (
  IFS=-
  git pull
  for d in "$r"/{*/*,*/*/*}/autobuild/cross-*/; do
    d=${d%/}
    read -d '' -r -a a <<< "${d##*}" # a=d.replace(/^.*\//, '').eachsplit(IFS)
    if [[ "${a[2]}" ]]; then
      mv "$d" "${d%/*}/${a[2]}-cross-${a[1]}" 
    else
      mv "$d" "${d%/*}/${a[1]}-cross"
    fi
  done
  git commit -am "*: apply new-ab3-archdirs"
  git push
) & done
wait
```

**Comment by Arthur2e5** [comment]
Anyway I prefer to do this fast… Be advised, we are gonna need a major version bump for this.

**Comment by MingcongBai** [comment]
Do it.

**Comment by Arthur2e5** [comment]
After writing this, I realize how brainfucking the names CROSS and ARCH are. Someday we will need to make them ABCROSS and ABHOST.

**Comment by Arthur2e5** [comment]
Oh shit Oh shit Bai we triggered a trap in CORE!

We assumed ARCH to be ABHOST.

**Comment by Arthur2e5** [comment]
@JeffBai By doing that we are checking against the builder arch instead of the runner arch. This is not good.

**Comment by MingcongBai** [comment]
> @JeffBai By doing that we are checking against the builder arch instead of the runner arch. This is not good.

Got it. Will fix in a bit. The build test is far from beginning just yet...

**Comment by Arthur2e5** [comment]
Uh, let's fix that in ab.

**Comment by MingcongBai** [comment]
> Uh, let's fix that in ab.

Sounds good to me.

**Comment by Arthur2e5** [comment]
Oh I love breaking changes. Major version bumps are fantastic. Blow the world up!

**Comment by MingcongBai** [comment]
> Oh I love breaking changes. Major version bumps are fantastic. Blow the world up!

I will be working on backwards compatibility. Before that's done, no tags permitted.

**Comment by Arthur2e5** [comment]
For basic compatibility, I will add to `declare -n`'s.

**Comment by Arthur2e5** [comment]
Uh.. should I tell git master users like @Icenowy to change that line to `ARCH_FINDFILELIST=("autobuild/cross-$ARCH-$CROSS" "autobuild/cross-$CROSS" "autobuild/$ARCH" "autobuild")` for now?
