### ISSUE TITLE
arch: AVAILABLE_ARCH support

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/autobuild3#84]
Proposing support for listing on what arch the package **will** build, and those not on the list will not. For example:

```bash
AVAILABLE_ARCH="amd64"
```

Then, when running with `ARCH=amd64`, the build goes on as usual. If running on `ARCH=armel`, then...

```bash
[ERROR] Specified package cannot be built on arch: armel.
```

When `AVAILABLE_ARCH` is left blank, then all architectures are free to build this package.

**Comment by Arthur2e5** [comment]
Added a blacklist scheme.

```
# foo/defines
arch_exclude 'arm*'
```

**Comment by MingcongBai** [comment]
Can this still be factor'd into a variable? That would really make life easier...

**Comment by Arthur2e5** [comment]
Ugh, why a variable…

**Comment by MingcongBai** [comment]
> Ugh, why a variable…

Imagine out of nowhere comes a scheme-like command...

**Comment by Arthur2e5** [comment]
Hmm…… I can move this to `defines` actually.

With a single extglob… Right.

**Comment by Arthur2e5** [comment]
But still I have to say I prefer blacklisting so…

**Comment by MingcongBai** [comment]
Well simply assume whenever a file is sourced with extglob...

**Comment by MingcongBai** [comment]
> But still I have to say I prefer blacklisting so…

Fine by me.

**Comment by Arthur2e5** [comment]
With the `negate` glob operator, you can do something like `!(amd64|armel)`.

**Comment by MingcongBai** [comment]
Why would I want that...?

**Comment by Arthur2e5** [comment]
Because not(not(amd64 or armel)) is amd64 or armel, and that's what available means.

**Comment by MingcongBai** [comment]
(God... I am always mixing this up with "given that") Don't mind me.
