### ISSUE TITLE
arch: noarch for data-only packages

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/autobuild3#89]
Currently Autobuild3 will not accept any data packages as architectural neutral, same for Java and other similar packages...

Well this should be done in a timely manner before more unnecessary work is done on future architectural ports.

**Comment by Arthur2e5** [comment]
* Allocate magic-arch NOARCH for `$ABHOST`
* Special handling in pm and archive

**Comment by Arthur2e5** [comment]
Should work now. 6e2bd71, 9e8cea3, e5175ab.
```sh
# defines
ABHOST=NOARCH
```

**Comment by MingcongBai** [comment]
Yep. https://github.com/AOSC-Dev/autobuild3/commit/9e8cea3bf0438b37285871f58fef17f416eb18b8 is starting to cause problem when building `binutils` on `armel`. Our `armel` uses quite a weird triplet as shown below. However it is by no mean a convention for `binutils` executables to be prefixed with `host`, with `--host` specified, `binutils` is assuming a cross build.

```
make[2]: armv7a-hardfloat-linux-gnueabi-ar: Command not found
```

**Comment by MingcongBai** [comment]
May I revert that commit to make it safe?

**Comment by Arthur2e5** [comment]
It's not about noarch. The host decision is done in ABHOST/ABBUILD.

Use `[[ $ABHOST != $ABBUILD ]]` instead of `[[ $HOST ]]`.

**Comment by MingcongBai** [comment]
That's why I mentioned https://github.com/AOSC-Dev/autobuild3/commit/9e8cea3bf0438b37285871f58fef17f416eb18b8 ...

**Comment by MingcongBai** [comment]
@Arthur2e5 We have another issue... `autobuild-aoscarchive` needs to be able to handle `noarch` packages somehow.

**Comment by MingcongBai** [comment]
May I drop `NOARCH` as `noarch`... as it really looks bad as a part of a file name.

**Comment by Arthur2e5** [comment]
I thought uppercase will make it look different and.. but yeah, it looks bad, so it's evil.

**Comment by MingcongBai** [comment]
Implemented and working. Closing.
