### ISSUE TITLE
PKGDEP: Specifying version in defines?

### ISSUE THREAD

**Issue by Arthur2e5** [AOSC-Dev/autobuild3#9]
Consider adding version setting in PKGDEP, so now we should have something like
```Bash
PKGDEP="foo>=2.1 bar=8.1 baz<3.2"
```
We need something to make this work.

> I have a great idea! All I need is a programmer and $1M to earn a lot of money.

**Comment by MingcongBai** [comment]
Solved as soon as autobuild3 is out, right? @Icenowy

**Comment by Arthur2e5** [comment]
Done reference impl (draft) in ab2: https://github.com/AOSC-Dev/autobuild/blob/master/PAKMGR.md

**Comment by MingcongBai** [comment]
Would you like to forward port the changes... I can't comprehend how I will do it.

**Comment by Arthur2e5** [comment]
@MingcongBai is there any package using the current ab3's `OPpkgname` syntax?

**Comment by MingcongBai** [comment]
OPpkgname?

**Comment by MingcongBai** [comment]
No. As far as I know.

**Comment by MingcongBai** [comment]
Even there is, when I happen Togo through them. I will rebuild no matter what.

**Comment by Arthur2e5** [comment]
15205b7 test pending

**Comment by Arthur2e5** [comment]
Merged `ab2-port`.
